# Generated by Django 5.1.1 on 2024-09-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foodentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='foods',
        ),
    ]
